services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
      INTERVAL: 10
      REQUEST_TIMEOUT: 2
      WORKERS_COUNT: 3
    ports:
      - "8080:8080" 
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sslowmm
    ports:
    - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: sslowmm
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: Anton
      ME_CONFIG_BASICAUTH_PASSWORD: mmm
    ports:
      - "127.0.0.1:8081:8081"

volumes:
  mongodb_data: